local _, ns = ...
local L = ns.L
if not L then
  return
end

L["ADDON_NAME"] = "Enhanced Crafting"
L["OPT_MAIN_DESC"] = "Crafting and crafter-finding helper."
L["OPT_RESET_ALL"] = "Reset Defaults"
L["OPT_ENABLE_ADDON"] = "Enable Addon"
L["OPT_CHANNEL_HEADER"] = "FindCrafter Channel"
L["OPT_AUTO_JOIN"] = "Auto Join FindCrafter Channel"
L["OPT_JOIN_DELAY"] = "Auto Join Delay"
L["OPT_JOIN_DELAY_DESC"] = "Seconds after login before attempting to join FindCrafter channel."
L["OPT_REMINDER_HEADER"] = "Order Reminder"
L["OPT_REMINDER_ENABLE"] = "Enable Reminder"
L["OPT_REMINDER_PREVIEW"] = "Show for Setup"
L["OPT_REMINDER_PREVIEW_DESC"] = "Shows the reminder frame without timer while settings are open."
L["OPT_REMINDER_TEXT"] = "Reminder Text"
L["OPT_REMINDER_PATTERN"] = "System Message Pattern"
L["OPT_REMINDER_PATTERN_DESC"] = "Simple substring match in CHAT_MSG_SYSTEM."
L["OPT_REMINDER_DURATION"] = "Reminder Duration"
L["OPT_REMINDER_FONT_SIZE"] = "Reminder Font Size"
L["OPT_REMINDER_ANCHOR"] = "Reminder Anchor"
L["OPT_REMINDER_X"] = "Reminder X"
L["OPT_REMINDER_Y"] = "Reminder Y"
L["OPT_REMINDER_WIDTH"] = "Reminder Width"
L["OPT_REMINDER_HEIGHT"] = "Reminder Height"
L["OPT_REMINDER_SOUND"] = "Reminder Sound Path"
L["OPT_REMINDER_PLAY_SOUND"] = "Play Selected Sound"
L["OPT_SOUND_CHANNEL"] = "Sound Channel"
L["SOUND_MASTER"] = "Master"
L["SOUND_MUSIC"] = "Music"
L["SOUND_AMBIENCE"] = "Ambience"
L["SOUND_DIALOG"] = "Dialog"
L["SOUND_RAID_WARNING"] = "Raid Warning"
L["SOUND_ALARM_CLOCK"] = "Alarm Clock"
L["SOUND_LEVEL_UP"] = "Level Up"
L["SOUND_MAP_PING"] = "Map Ping"
L["SOUND_READY_CHECK"] = "Ready Check"
L["SOUND_FLAG_TAKEN"] = "Flag Taken"
L["SOUND_CUSTOM_SAVED"] = "Custom Saved Path"
L["OPT_TOOLS_HEADER"] = "Tools"
L["OPT_DEBUG"] = "Debug Logging"
L["OPT_TRACE"] = "Trace UI State"
L["OPT_TRACE_DESC"] = "Captures Professions/Customer Orders state transitions. Use /ecraft dump to print buffer."
L["OPT_JOIN_NOW"] = "Join Channel Now"
L["OPT_TEST_REMINDER"] = "Test Reminder"
L["OPT_RELOAD_HOOKS"] = "Reload Hooks"

L["REMINDER_TEXT_DEFAULT"] = "New Crafting Order"
L["REMINDER_PATTERN_DEFAULT"] = "new Personal Crafting Order"
L["BTN_PLACE_ORDER"] = "Place Order"
L["BTN_FIND"] = "Find"
L["BTN_JOIN"] = "Join"
L["LABEL_UNLOCK_ALL"] = "Unlock All"
L["FORMAT_SKILL"] = "Skill: %d/%d"

L["STATUS_NOT_LOADED"] = "|cff999999not loaded|r"
L["STATUS_NOT_LEARNED"] = "|cffff0000not learned|r"
L["STATUS_OK"] = "|cff00ff00ok|r"

L["ADDON_LOADED"] = "|cff00ff00 /ecraft|r settings."
L["PROF_UI_UNAVAILABLE"] = "Professions UI is not available yet. Open professions once, then use /ecraft reload."
L["PROF_UI_LAYOUT_UNEXPECTED"] = "Unexpected Professions UI layout. Open Orders form first, then use /ecraft reload."
L["TRACE_EMPTY"] = "Trace buffer is empty."
L["TRACE_DUMP_BEGIN"] = "=== EnhancedCrafting trace dump ==="
L["TRACE_DUMP_END"] = "=== End trace dump ==="
L["TRACE_SAVED_TO_SV"] = "Trace also saved to SavedVariables: EnhancedCraftingDB.global.lastTraceDump"

L["PROBE_PF_NIL"] = "ProfessionsFrame is nil."
L["PROBE_BEGIN"] = "=== ProfessionsFrame probe ==="
L["PROBE_END"] = "=== End probe ==="
L["PROBE_SHOWN"] = "shown:"
L["PROBE_NAME"] = "name:"
L["PROBE_CRAFTING_PAGE"] = "CraftingPage:"
L["PROBE_ORDERS_PAGE"] = "OrdersPage:"
L["PROBE_KNOWN_TAB_GLOBALS"] = "Known tab globals:"
L["PROBE_METHODS"] = "Methods:"

L["DEBUG_SKIP_SEND_IN_INSTANCE"] = "Skip SendCommMessage in instance due to restrictions."
L["DEBUG_SEND_FAILED"] = "SendCommMessage failed."
L["DEBUG_GET_CRAFTING_OPERATION_FAILED"] = "GetCraftingOperationInfo failed for recipe"

L["SLASH_RELOADED"] = "Hooks and UI reloaded."
L["SLASH_CHANNEL_STATE"] = "Channel state: "
L["SLASH_DEBUG"] = "Debug: "
L["SLASH_TRACE"] = "Trace: "
L["SLASH_BLIZZMOVE_NOTE"] = "Note: BlizzMove is loaded and may affect Professions/CustomerOrders panel state."
L["SLASH_ENABLED"] = "Enabled."
L["SLASH_DISABLED"] = "Disabled."
L["SLASH_DELAY_SET"] = "Delay set to %d."
L["SLASH_DELAY_USAGE"] = "Usage: /ecraft delay <1-180>"
L["SLASH_HELP"] = "Commands: /ecraft config | reload | join | debug | trace [on/off] | dump | probe | state | remind | enable | disable | delay <1-180>"
L["MSG_SETTINGS_RESET"] = "Enhanced Crafting: settings reset to defaults."
L["MSG_SOUND_PLAY_FAILED"] = "Could not play selected sound on current channels."

L["ANCHOR_CENTER"] = "Center"
L["ANCHOR_TOPLEFT"] = "Top Left"
L["ANCHOR_TOP"] = "Top"
L["ANCHOR_TOPRIGHT"] = "Top Right"
L["ANCHOR_LEFT"] = "Left"
L["ANCHOR_RIGHT"] = "Right"
L["ANCHOR_BOTTOMLEFT"] = "Bottom Left"
L["ANCHOR_BOTTOM"] = "Bottom"
L["ANCHOR_BOTTOMRIGHT"] = "Bottom Right"
