local _, ns = ...
local L = ns.L
if not L then
  return
end

if GetLocale() ~= "ruRU" then
  return
end

L["ADDON_NAME"] = "Enhanced Crafting"
L["OPT_MAIN_DESC"] = "Помощник крафта и поиска крафтеров."
L["OPT_RESET_ALL"] = "Сбросить настройки"
L["OPT_ENABLE_ADDON"] = "Включить аддон"
L["OPT_CHANNEL_HEADER"] = "Канал FindCrafter"
L["OPT_AUTO_JOIN"] = "Автовход в канал FindCrafter"
L["OPT_JOIN_DELAY"] = "Задержка автовхода"
L["OPT_JOIN_DELAY_DESC"] = "Сколько секунд после входа ждать перед подключением к каналу FindCrafter."
L["OPT_REMINDER_HEADER"] = "Напоминание о заказе"
L["OPT_REMINDER_ENABLE"] = "Напоминание"
L["OPT_REMINDER_PREVIEW"] = "Показать окно"
L["OPT_REMINDER_PREVIEW_DESC"] = "Показывает окно напоминания без таймера, пока открыты настройки."
L["OPT_REMINDER_TEXT"] = "Текст напоминания"
L["OPT_REMINDER_PATTERN"] = "Шаблон системного сообщения"
L["OPT_REMINDER_PATTERN_DESC"] = "Простая проверка на подстроку в CHAT_MSG_SYSTEM."
L["OPT_REMINDER_DURATION"] = "Длительность напоминания"
L["OPT_REMINDER_FONT_SIZE"] = "Размер шрифта"
L["OPT_REMINDER_ANCHOR"] = "Якорь напоминания"
L["OPT_REMINDER_X"] = "Координата X"
L["OPT_REMINDER_Y"] = "Координата Y"
L["OPT_REMINDER_WIDTH"] = "Ширина окна"
L["OPT_REMINDER_HEIGHT"] = "Высота окна"
L["OPT_REMINDER_SOUND"] = "Звук напоминания"
L["OPT_REMINDER_PLAY_SOUND"] = "Проиграть выбранный звук"
L["OPT_SOUND_CHANNEL"] = "Звуковой канал"
L["SOUND_MASTER"] = "Master"
L["SOUND_MUSIC"] = "Музыка"
L["SOUND_AMBIENCE"] = "Окружение"
L["SOUND_DIALOG"] = "Диалоги"
L["SOUND_RAID_WARNING"] = "Предупреждение рейда"
L["SOUND_ALARM_CLOCK"] = "Будильник"
L["SOUND_LEVEL_UP"] = "Повышение уровня"
L["SOUND_MAP_PING"] = "Пинг карты"
L["SOUND_READY_CHECK"] = "Проверка готовности"
L["SOUND_FLAG_TAKEN"] = "Флаг захвачен"
L["SOUND_CUSTOM_SAVED"] = "Сохраненный путь"
L["OPT_TOOLS_HEADER"] = "Инструменты"
L["OPT_DEBUG"] = "Лог отладки"
L["OPT_TRACE"] = "Трассировка UI"
L["OPT_TRACE_DESC"] = "Собирает переходы состояний Professions/Customer Orders. Используйте /ecraft dump для вывода буфера."
L["OPT_JOIN_NOW"] = "Подключиться к каналу"
L["OPT_TEST_REMINDER"] = "Тест напоминания"
L["OPT_RELOAD_HOOKS"] = "Перезагрузить хуки"

L["REMINDER_TEXT_DEFAULT"] = "Новый заказ на изготовление"
L["REMINDER_PATTERN_DEFAULT"] = "новый персональный заказ"
L["BTN_PLACE_ORDER"] = "Стол заказов"
L["BTN_FIND"] = "Найти"
L["BTN_JOIN"] = "Войти"
L["LABEL_UNLOCK_ALL"] = "Открыть все"
L["FORMAT_SKILL"] = "Навык: %d/%d"

L["STATUS_NOT_LOADED"] = "|cff999999не загружено|r"
L["STATUS_NOT_LEARNED"] = "|cffff0000не изучено|r"
L["STATUS_OK"] = "|cff00ff00ок|r"

L["ADDON_LOADED"] = "|cff00ff00 /ecraft|r настройки."
L["PROF_UI_UNAVAILABLE"] = "UI профессий пока недоступен. Откройте окно профессии один раз и выполните /ecraft reload."
L["PROF_UI_LAYOUT_UNEXPECTED"] = "Неожиданный макет UI профессий. Откройте форму заказов и выполните /ecraft reload."
L["TRACE_EMPTY"] = "Буфер трассировки пуст."
L["TRACE_DUMP_BEGIN"] = "=== Дамп трассировки EnhancedCrafting ==="
L["TRACE_DUMP_END"] = "=== Конец дампа ==="
L["TRACE_SAVED_TO_SV"] = "Трассировка сохранена в SavedVariables: EnhancedCraftingDB.global.lastTraceDump"

L["PROBE_PF_NIL"] = "ProfessionsFrame равен nil."
L["PROBE_BEGIN"] = "=== Проверка ProfessionsFrame ==="
L["PROBE_END"] = "=== Конец проверки ==="
L["PROBE_SHOWN"] = "показан:"
L["PROBE_NAME"] = "имя:"
L["PROBE_CRAFTING_PAGE"] = "CraftingPage:"
L["PROBE_ORDERS_PAGE"] = "OrdersPage:"
L["PROBE_KNOWN_TAB_GLOBALS"] = "Известные глобальные вкладки:"
L["PROBE_METHODS"] = "Методы:"

L["DEBUG_SKIP_SEND_IN_INSTANCE"] = "Пропуск SendCommMessage в инсте из-за ограничений."
L["DEBUG_SEND_FAILED"] = "SendCommMessage завершился ошибкой."
L["DEBUG_GET_CRAFTING_OPERATION_FAILED"] = "GetCraftingOperationInfo не сработал для рецепта"

L["SLASH_RELOADED"] = "Хуки и UI перезагружены."
L["SLASH_CHANNEL_STATE"] = "Состояние канала: "
L["SLASH_DEBUG"] = "Отладка: "
L["SLASH_TRACE"] = "Трассировка: "
L["SLASH_BLIZZMOVE_NOTE"] = "Примечание: загружен BlizzMove, он может влиять на состояние панелей Professions/CustomerOrders."
L["SLASH_ENABLED"] = "Включено."
L["SLASH_DISABLED"] = "Выключено."
L["SLASH_DELAY_SET"] = "Задержка установлена: %d."
L["SLASH_DELAY_USAGE"] = "Использование: /ecraft delay <1-180>"
L["SLASH_HELP"] = "Команды: /ecraft config | reload | join | debug | trace [on/off] | dump | probe | state | remind | enable | disable | delay <1-180>"
L["MSG_SETTINGS_RESET"] = "Enhanced Crafting: настройки сброшены по умолчанию."
L["MSG_SOUND_PLAY_FAILED"] = "Не удалось проиграть выбранный звук на текущих каналах."

L["ANCHOR_CENTER"] = "Центр"
L["ANCHOR_TOPLEFT"] = "Сверху слева"
L["ANCHOR_TOP"] = "Сверху"
L["ANCHOR_TOPRIGHT"] = "Сверху справа"
L["ANCHOR_LEFT"] = "Слева"
L["ANCHOR_RIGHT"] = "Справа"
L["ANCHOR_BOTTOMLEFT"] = "Снизу слева"
L["ANCHOR_BOTTOM"] = "Снизу"
L["ANCHOR_BOTTOMRIGHT"] = "Снизу справа"
