local _, ns = ...
local L = ns.L
if not L then
  return
end

if GetLocale() ~= "zhCN" then
  return
end

L["ADDON_NAME"] = "Enhanced Crafting"
L["OPT_MAIN_DESC"] = "制作和寻找工匠助手。"
L["OPT_RESET_ALL"] = "重置默认设置"
L["OPT_ENABLE_ADDON"] = "启用插件"
L["OPT_CHANNEL_HEADER"] = "寻找工匠频道"
L["OPT_AUTO_JOIN"] = "自动加入寻找工匠频道"
L["OPT_JOIN_DELAY"] = "自动加入延迟"
L["OPT_JOIN_DELAY_DESC"] = "登录后几秒钟尝试加入寻找工匠频道。"
L["OPT_REMINDER_HEADER"] = "订单提醒"
L["OPT_REMINDER_ENABLE"] = "启用提醒"
L["OPT_REMINDER_PREVIEW"] = "显示设置"
L["OPT_REMINDER_PREVIEW_DESC"] = "设置打开时显示提醒框架，无计时器。"
L["OPT_REMINDER_TEXT"] = "提醒文本"
L["OPT_REMINDER_PATTERN"] = "系统消息模式"
L["OPT_REMINDER_PATTERN_DESC"] = "在聊天中的简单子字符串匹配。"
L["OPT_REMINDER_DURATION"] = "提醒持续时间"
L["OPT_REMINDER_FONT_SIZE"] = "提醒字体大小"
L["OPT_REMINDER_ANCHOR"] = "提醒锚点"
L["OPT_REMINDER_X"] = "提醒X"
L["OPT_REMINDER_Y"] = "提醒Y"
L["OPT_REMINDER_WIDTH"] = "提醒宽度"
L["OPT_REMINDER_HEIGHT"] = "提醒高度"
L["OPT_REMINDER_SOUND"] = "提醒声音路径"
L["OPT_REMINDER_PLAY_SOUND"] = "播放选定声音"
L["OPT_SOUND_CHANNEL"] = "声音频道"
L["SOUND_MASTER"] = "主音量"
L["SOUND_MUSIC"] = "音乐"
L["SOUND_AMBIENCE"] = "环境音"
L["SOUND_DIALOG"] = "对话"
L["SOUND_RAID_WARNING"] = "团队警告"
L["SOUND_ALARM_CLOCK"] = "闹钟"
L["SOUND_LEVEL_UP"] = "升级"
L["SOUND_MAP_PING"] = "地图Ping"
L["SOUND_READY_CHECK"] = "就绪检查"
L["SOUND_FLAG_TAKEN"] = "旗帜被夺"
L["SOUND_CUSTOM_SAVED"] = "自定义保存路径"
L["OPT_TOOLS_HEADER"] = "工具"
L["OPT_DEBUG"] = "调试日志"
L["OPT_TRACE"] = "跟踪UI状态"
L["OPT_TRACE_DESC"] = "捕获职业/客户订单状态转换。使用 /ecraft dump 打印缓冲区。"
L["OPT_JOIN_NOW"] = "立即加入频道"
L["OPT_TEST_REMINDER"] = "测试提醒"
L["OPT_RELOAD_HOOKS"] = "重新加载钩子"

L["REMINDER_TEXT_DEFAULT"] = "新制作订单"
L["REMINDER_PATTERN_DEFAULT"] = "新个人制作订单"
L["BTN_PLACE_ORDER"] = "下订单"
L["BTN_FIND"] = "寻找"
L["LABEL_UNLOCK_ALL"] = "解锁全部"
L["FORMAT_SKILL"] = "技能：%d/%d"

L["STATUS_NOT_LOADED"] = "|cff999999未加载|r"
L["STATUS_NOT_LEARNED"] = "|cffff0000未学习|r"
L["STATUS_OK"] = "|cff00ff00确定|r"

L["ADDON_LOADED"] = "|cff00ff00 /ecraft|r 设置。"
L["PROF_UI_UNAVAILABLE"] = "职业UI尚未可用。打开职业一次，然后使用 /ecraft reload。"
L["PROF_UI_LAYOUT_UNEXPECTED"] = "意外的职业UI布局。首先打开订单表单，然后使用/ecraft reload。"
L["TRACE_EMPTY"] = "跟踪缓冲区为空。"
L["TRACE_DUMP_BEGIN"] = "=== Enhanced Crafting 跟踪转储 ==="
L["TRACE_DUMP_END"] = "=== 结束跟踪转储 ==="
L["TRACE_SAVED_TO_SV"] = "跟踪也保存到SavedVariables：EnhancedCraftingDB.global.lastTraceDump"

L["PROBE_PF_NIL"] = "ProfessionsFrame为空。"
L["PROBE_BEGIN"] = "=== ProfessionsFrame探测 ==="
L["PROBE_END"] = "=== 结束探测 ==="
L["PROBE_SHOWN"] = "显示："
L["PROBE_NAME"] = "名称："
L["PROBE_CRAFTING_PAGE"] = "制作页面："
L["PROBE_ORDERS_PAGE"] = "订单页面："
L["PROBE_KNOWN_TAB_GLOBALS"] = "已知标签全局变量："
L["PROBE_METHODS"] = "方法："

L["DEBUG_SKIP_SEND_IN_INSTANCE"] = "由于限制，在副本中跳过发送 SendCommMessage。"
L["DEBUG_SEND_FAILED"] = "SendCommMessage 失败。"
L["DEBUG_GET_CRAFTING_OPERATION_FAILED"] = "配方的 GetCraftingOperationInfo 失败"

L["SLASH_RELOADED"] = "钩子和用户界面已重新加载。"
L["SLASH_CHANNEL_STATE"] = "频道状态："
L["SLASH_DEBUG"] = "调试："
L["SLASH_TRACE"] = "跟踪："
L["SLASH_BLIZZMOVE_NOTE"] = "注意：BlizzMove已加载，可能影响职业/客户订单面板状态。"
L["SLASH_ENABLED"] = "已启用。"
L["SLASH_DISABLED"] = "已禁用。"
L["SLASH_DELAY_SET"] = "延迟设置为%d。"
L["SLASH_DELAY_USAGE"] = "用法：/ecraft delay <1-180>"
L["SLASH_HELP"] = "命令：/ecraft config | reload | join | debug | trace [on/off] | dump | probe | state | remind | enable | disable | delay <1-180>"
L["MSG_SETTINGS_RESET"] = "增强制作：设置重置为默认。"
L["MSG_SOUND_PLAY_FAILED"] = "无法在当前频道播放选定声音。"

L["ANCHOR_CENTER"] = "中心"
L["ANCHOR_TOPLEFT"] = "左上"
L["ANCHOR_TOP"] = "顶部"
L["ANCHOR_TOPRIGHT"] = "右上"
L["ANCHOR_LEFT"] = "左侧"
L["ANCHOR_RIGHT"] = "右侧"
L["ANCHOR_BOTTOMLEFT"] = "左下"
L["ANCHOR_BOTTOM"] = "底部"
L["ANCHOR_BOTTOMRIGHT"] = "右下"
